name: Links Checker

on:
  workflow_dispatch:
  schedule:
      - cron: "0 0 1,15 * *" # twice a month

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.10.0

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Broken Link Detected (Help Wanted)
          content-filepath: ./lychee/out.md
          labels: report, automated issue, good first issue
